### ISSUE TITLE
Bad month

### ISSUE THREAD

**Issue by Baterka** [kub1x/rodnecislo#29]
For input "970301/0152" I am getting month "2". Correct is "3" (March).

 `rc.month()` is from zero? 0 = January?

**Comment by kub1x** [comment]
@Baterka exactly, as mentioned in README, `rc.month()` returns zero based number of month. This is standard among date libraries. It is safe to use `rc.month() + 1` to get correct month number. You could also use `rc.birthDateAsString()` to get "czech" format of date or library such as [Moment.js](https://momentjs.com) as so: `moment(rc.birthDate())`. 

```javascript
let rc = rodnecislo('111213/3121')

rc.isMale()     // true
rc.isFemale()   // false

rc.year()       // 2011
rc.month()      // 11 - zero based month
rc.day()        // 13

rc.birthDate()  // new Date(2011, 11, 13) - "Tue Dec 13 2011 00:00:00 GMT+0100 (CET)"
rc.birthDateAsString() // "13.12.2011" - the Czech date format
```
