### ISSUE TITLE
Validate length of numbers

### ISSUE THREAD

**Issue by Bubomir** [kub1x/rodnecislo#51]
Hi would be possible add some strict validation also on length of numbers ? Because I try some examples and

    console.log(rodnecislo('9206278653').isValid()) // => true
    console.log(rodnecislo('9206278653415161131868186').isValid()) // => true
but also this is valid 

    console.log(rodnecislo('9206278653fwefwefewfe').isValid()) // => true

ENV: package version: 1.5.6

thanks

**Comment by kub1x** [comment]
@Bubomir thanks for the catch. 

The first case seems valid as the slash is optional. It is really just a visual helper and have no syntax value as the first 6 digits are fixed position. Do you need strict validation to also forbid missing slash?

I've added boundaries to the regex, so the other two are fixed and tested now in 1.6.0. 

Díky! 

PS: I'd appreciate more info on slovak version, if it is any different, as I didn't find much resources on it.
